name: Cleanup Preview

on: [delete]

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Deploy Key
        run: |
          echo "${{secrets.DEPLOY_KEY}}" > deploy_key
          chmod 600 ./deploy_key
      - name: Delete Deploy
        run: ssh -i ./deploy_key -o StrictHostKeyChecking=no deployer@ec-nordbund.de "rm -r /webpage/preview.ec-nordbund.de/${{ github.event.ref }}"
